// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_OLwlzuEfSVMnFMH_EK2OQAi0_5jrS3k',
    appId: '1:555958852637:web:364200f8fff06ed7db7af4',
    messagingSenderId: '555958852637',
    projectId: 'akilli-ev-sistemi-f3d61',
    authDomain: 'akilli-ev-sistemi-f3d61.firebaseapp.com',
    storageBucket: 'akilli-ev-sistemi-f3d61.firebasestorage.app',
    measurementId: 'G-8TSQ7XR47R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqIRbUb71IhBnpMnmKz9sJxQz37oAQrus',
    appId: '1:555958852637:android:d696d04801fa4d85db7af4',
    messagingSenderId: '555958852637',
    projectId: 'akilli-ev-sistemi-f3d61',
    storageBucket: 'akilli-ev-sistemi-f3d61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVx-tq54_REMhS4F4VkOW1vB8sEvlRhqo',
    appId: '1:555958852637:ios:6be8fed7f135ac6fdb7af4',
    messagingSenderId: '555958852637',
    projectId: 'akilli-ev-sistemi-f3d61',
    storageBucket: 'akilli-ev-sistemi-f3d61.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVx-tq54_REMhS4F4VkOW1vB8sEvlRhqo',
    appId: '1:555958852637:ios:6be8fed7f135ac6fdb7af4',
    messagingSenderId: '555958852637',
    projectId: 'akilli-ev-sistemi-f3d61',
    storageBucket: 'akilli-ev-sistemi-f3d61.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_OLwlzuEfSVMnFMH_EK2OQAi0_5jrS3k',
    appId: '1:555958852637:web:dc4783cc871da9e4db7af4',
    messagingSenderId: '555958852637',
    projectId: 'akilli-ev-sistemi-f3d61',
    authDomain: 'akilli-ev-sistemi-f3d61.firebaseapp.com',
    storageBucket: 'akilli-ev-sistemi-f3d61.firebasestorage.app',
    measurementId: 'G-XJGCHPLWWV',
  );
}
